---
title: "TriNetX & PEDSnet: Case-Mix / Signatures Check Output"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_collapsed: yes
    toc_float: yes
---

```{r setup, include=FALSE}
# Default taken from R notebook behavior: when knitting, wd will always be location of notebook
base_dir <- '..'
Sys.setenv(PEDSNET_SKIP_REQUEST_EXECUTION=1)
tryCatch(source('../site/run.R'),
         error = function (e) message(e)) # May not be able to make db connection

# Set to "local" to read data from ../results, or another value to read from db
data_source <- if_else(config('execution_mode') == 'distribution', 'local', 'not_local')

require(tidyr)
require(knitr)
require(kableExtra)
require(stringr)
require(tibble)
require(ggplot2)
require(patchwork)
require(gt)

get_results <- function(tbl_name) {
  if (data_source == 'local') {
    rslt <- read_csv(paste0('../results/', tbl_name, '.csv'))
  }
  else {
    rslt <- results_tbl(tbl_name) %>% collect()
  }
rslt
}

prettify_kable <- function(data) {
  rslt <- data %>% kable(digits = 4, format.args = list(big.mark = ','))
  if (knitr::is_html_output()) rslt <- rslt %>%
    kable_styling(bootstrap_options = c("striped", "hover")) %>%
    column_spec(1, bold = T, border_right = T)
  rslt
}

site_list <- read_csv(file = '../results/COMBINED_case_mix_sept.csv') %>% 
  distinct(site_anon) %>% pull()

opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```

# Single Site Exploratory

## Full Population

```{r cm_ss_full, fig.height=6}

case_mix_summ_viz(process_output = read_csv(file = '../results/COMBINED_case_mix_sept.csv') %>%
                    filter(cohort == 'full'),
                  site_filter = site_list[1:6])

case_mix_summ_viz(process_output = read_csv(file = '../results/COMBINED_case_mix_sept.csv') %>%
                    filter(cohort == 'full'),
                  site_filter = site_list[7:12])

case_mix_summ_viz(process_output = read_csv(file = '../results/COMBINED_case_mix_sept.csv') %>%
                    filter(cohort == 'full'),
                  site_filter = site_list[13:18])

case_mix_summ_viz(process_output = read_csv(file = '../results/COMBINED_case_mix_sept.csv') %>%
                    filter(cohort == 'full'),
                  site_filter = site_list[19:26])

```

## SCD Cohort
```{r cm_ss_scd, fig.height=6}

case_mix_summ_viz(process_output = read_csv(file = '../results/COMBINED_case_mix_sept.csv') %>%
                    filter(cohort == 'scd'),
                  site_filter = site_list[1:6])

case_mix_summ_viz(process_output = read_csv(file = '../results/COMBINED_case_mix_sept.csv') %>%
                    filter(cohort == 'scd'),
                  site_filter = site_list[7:12])

case_mix_summ_viz(process_output = read_csv(file = '../results/COMBINED_case_mix_sept.csv') %>%
                    filter(cohort == 'scd'),
                  site_filter = site_list[13:18])

case_mix_summ_viz(process_output = read_csv(file = '../results/COMBINED_case_mix_sept.csv') %>%
                    filter(cohort == 'scd'),
                  site_filter = site_list[19:26])

```

# Multi Site Exploratory

## Full Cohort
```{r cm_ms_full, fig.height = 9}

case_mix_ms_viz(process_output = read_csv(file = '../results/COMBINED_case_mix_sept.csv') %>%
               filter(cohort == 'full'))


```

## SCD Cohort
```{r cm_ms_scd, fig.height = 9}

case_mix_ms_viz(process_output = read_csv(file = '../results/COMBINED_case_mix_sept.csv') %>%
               filter(cohort == 'scd'))

case_mix_ms_viz2(process_output = read_csv(file = '../results/COMBINED_case_mix_sept.csv') %>%
               filter(cohort == 'scd'))

```

# Alternate Multi Site Options {.tabset .tabset-pills}

## Alt 1 - Line Graph
```{r cm_ms_alt}

alt_full <- case_mix_ms_viz2(process_output = read_csv(file = '../results/COMBINED_case_mix_sept.csv') %>%
               filter(cohort == 'full'),
               cohort = 'Full')

alt_scd <- case_mix_ms_viz2(process_output = read_csv(file = '../results/COMBINED_case_mix_sept.csv') %>%
               filter(cohort == 'scd'), cohort = 'SCD')

alt_full[[1]]
alt_scd[[1]]

```

## Alt 2 - Dot Plot
```{r cm_ms_alt2}

alt_full[[2]]
alt_scd[[2]]

```

## Alt 3 - Dot and Line Plot
```{r cm_ms_alt3}

alt_full[[3]]
alt_scd[[3]]

```

# Anomaly Detection Output

## Combined Networks
### Full Cohort
```{r mix_anom_full}

mix_anon_combo <- trinetx_anom_detect(dat = 
                                        read_csv(file = '../results/COMBINED_case_mix_sept.csv') %>%
                                              filter(cohort == 'full',
                                                     !grepl('U', branch)) %>%
                                        mutate(prop_pts = prop_pts * 100,
                                           network = ifelse(grepl('HCO', site_anon),
                                                            'trinetx', 'pedsnet')),
                                      var_col = 'prop_pts',
                                      grp_vars = c('branch'))

mix_anon_graph <- trinetx_anom_viz(dat = mix_anon_combo,
                                   var_col = 'prop_pts',
                                   grp_col = 'branch')

mix_anon_graph[[1]]
mix_anon_graph[[2]]

```

### SCD Cohort
```{r mix_anom_scd}

mix_anon_combo <- trinetx_anom_detect(dat = 
                                        read_csv(file = '../results/COMBINED_case_mix_sept.csv') %>%
                                        filter(cohort=='scd') %>%
                                        mutate(prop_pts = prop_pts * 100,
                                               network = ifelse(grepl('HCO', site_anon),
                                                            'trinetx', 'pedsnet')),
                                      var_col = 'prop_pts',
                                      grp_vars = c('branch'))

mix_anon_graph <- trinetx_anom_viz(dat = mix_anon_combo,
                                   var_col = 'prop_pts',
                                   grp_col = 'branch')

mix_anon_graph[[1]]
mix_anon_graph[[2]]

```

## Each Network Separately
### Full Cohort
```{r mix_anom_full2}

mix_anon_combo <- trinetx_anom_detect(dat = 
                                        read_csv(file = '../results/COMBINED_case_mix_sept.csv') %>%
                                              filter(cohort == 'full',
                                                     !grepl('U', branch)) %>%
                                        mutate(prop_pts = prop_pts * 100,
                                           network = ifelse(grepl('HCO', site_anon),
                                                            'trinetx', 'pedsnet')),
                                      var_col = 'prop_pts',
                                      grp_vars = c('branch','network'))

mix_anon_graph <- trinetx_anom_viz(dat = mix_anon_combo,
                                   var_col = 'prop_pts',
                                   grp_col = 'branch')

mix_anon_graph[[1]]
mix_anon_graph[[2]]

```

### SCD Cohort
```{r mix_anom_scd2}

mix_anon_combo <- trinetx_anom_detect(dat = 
                                        read_csv(file = '../results/COMBINED_case_mix_sept.csv') %>%
                                        filter(cohort=='scd') %>%
                                        mutate(prop_pts = prop_pts * 100,
                                               network = ifelse(grepl('HCO', site_anon),
                                                            'trinetx', 'pedsnet')),
                                      var_col = 'prop_pts',
                                      grp_vars = c('branch','network'))

mix_anon_graph <- trinetx_anom_viz(dat = mix_anon_combo,
                                   var_col = 'prop_pts',
                                   grp_col = 'branch')

mix_anon_graph[[1]]
mix_anon_graph[[2]]

```