---
title: "PEDSnet & TriNetX Combined Output"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_collapsed: yes
    toc_float: yes
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, 
  output_file = paste0('combined_network_output_', format(Sys.time(), '%Y%m%d'), '.html') )})
---

```{r setup, include=FALSE}
# Default taken from R notebook behavior: when knitting, wd will always be location of notebook
base_dir <- '..'
Sys.setenv(PEDSNET_SKIP_REQUEST_EXECUTION=1)
tryCatch(source('../site/run.R'),
         error = function (e) message(e)) # May not be able to make db connection

# Set to "local" to read data from ../results, or another value to read from db
data_source <- if_else(config('execution_mode') == 'distribution', 'local', 'not_local')

require(tidyr)
require(knitr)
require(kableExtra)
require(stringr)
require(tibble)
require(ggplot2)
require(ggiraph)
require(plotly)

get_results <- function(tbl_name) {
  if (data_source == 'local') {
    rslt <- read_csv(paste0('../results/', tbl_name, '.csv'))
  }
  else {
    rslt <- results_tbl(tbl_name) %>% collect()
  }
rslt
}

prettify_kable <- function(data) {
  rslt <- data %>% kable(digits = 4, format.args = list(big.mark = ','))
  if (knitr::is_html_output()) rslt <- rslt %>%
    kable_styling(bootstrap_options = c("striped", "hover")) %>%
    column_spec(1, bold = T, border_right = T)
  rslt
}

opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

```

## Couplets
```{r cplt_exp}

#' Cohort Overlap of Both Cohorts
couplets_prop_combined <- 
  ms_exp_nt(read_csv(file = '../results/COMBINED_couplets.csv') %>% filter(cohort=='combined') %>% 
              filter(! str_detect(site_anon,'all|ALL')), 'prop') +
  ggtitle('Proportion of Combined Over Total in Both')

couplets_prop_combined

#' Proportion of Patients in Cohort 2 who are in Cohort 1
couplets_prop_cohort_1 <- 
  ms_exp_nt(read_csv(file = '../results/COMBINED_couplets.csv') %>% filter(cohort=='cohort_1_denom_prop') %>% 
              filter(! str_detect(site_anon,'all|ALL')), 'prop') +
  ggtitle('Proportion of Cohort 2 in Cohort 1')

couplets_prop_cohort_1

```

#### Anomaly Detection (TriNetX sites only)

```{r cplt_anom}

couplet_anomaly_plot_trinetx <- ms_anom_nt(process_output=
                                             read_csv(file = '../results/COMBINED_couplets_anom.csv') %>% 
                                             filter(site %in% c('HCO1','HCO2','HCO3',
                                                                'HCO4','HCO5','HCO6',
                                                                'HCO7','HCO8','HCO9','HCO10',
                                                                'HCO11','HCO12','HCO13')),
                                           comparison_col='prop',
                                           variable='couplet_name')

couplet_anomaly_plot_trinetx

```

## Signatures / Case-Mix

```{r mix}

casemix_output <- ms_exp_nt2(process_output = read_csv(file = '../results/COMBINED_case_mix.csv'),
                             check_string = 'Branch',
                             y_col = 'branch',
                             descriptor_col = 'description')

casemix_output

```

## Coverage Overlap

```{r cvg}

cvg_output <- ms_exp_nt2(process_output = read_csv(file = '../results/COMBINED_cvg_overlap.csv'),
                             check_string = 'Fact Group',
                             y_col = 'fact_group',
                             descriptor_col = 'fact_long')

cvg_output

```

## Stability Over Time

Here, we are using the normalized patient count computed using the heuristic developed by the PEDSnet team. This is  `month / ((month-1)*.25 + (month+1)*.25 + (month-12)*.5)`

### Combined (All Sites Included)
```{r fot}

check_type <- 'hypertension'

fot_all <- euclidean_output(process_output = read_csv('../results/FOT_combined.csv'),
                             output_var = 'check',
                             filter_variable = check_type)

fot_all[[1]]
fot_all[[2]]
fot_all[[3]]
```

### Separated (Different Graphs per Network)

```{r fot_sep}
fot_chop <- euclidean_output(process_output = read_csv('../results/FOT_chop.csv'),
                              output_var = 'check',
                              filter_variable = check_type)

fot_chop[[1]]
fot_chop[[2]]
fot_chop[[3]]


fot_tnx <- euclidean_output(process_output = read_csv('../results/FOT_trinetx.csv'),
                             output_var = 'check',
                             filter_variable = check_type)

fot_tnx[[1]]
fot_tnx[[2]]
fot_tnx[[3]]


```