---
title: "TriNetX & PEDSnet: Couplets"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_collapsed: yes
    toc_float: yes
---

```{r setup, include=FALSE}
# Default taken from R notebook behavior: when knitting, wd will always be location of notebook
base_dir <- '..'
Sys.setenv(PEDSNET_SKIP_REQUEST_EXECUTION=1)
tryCatch(source('../site/run.R'),
         error = function (e) message(e)) # May not be able to make db connection

# Set to "local" to read data from ../results, or another value to read from db
data_source <- if_else(config('execution_mode') == 'distribution', 'local', 'not_local')

require(tidyr)
require(knitr)
require(kableExtra)
require(stringr)
require(tibble)
require(ggplot2)
require(gt)

get_results <- function(tbl_name) {
  if (data_source == 'local') {
    rslt <- read_csv(paste0('../results/', tbl_name, '.csv'))
  }
  else {
    rslt <- results_tbl(tbl_name) %>% collect()
  }
rslt
}

prettify_kable <- function(data) {
  rslt <- data %>% kable(digits = 4, format.args = list(big.mark = ','))
  if (knitr::is_html_output()) rslt <- rslt %>%
    kable_styling(bootstrap_options = c("striped", "hover")) %>%
    column_spec(1, bold = T, border_right = T)
  rslt
}

site_list <- read_csv(file = '../results/COMBINED_couplets.csv') %>% 
  distinct(site_anon) %>% filter(!is.na(site_anon), site_anon != 'ALL') %>% pull()

opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

```

# Single Site Exploratory
```{r}

couplets_ss_viz(process_output = read_csv(file = '../results/COMBINED_couplets.csv') %>%
                  filter(site_anon %in% site_list[1:6]))

couplets_ss_viz(process_output = read_csv(file = '../results/COMBINED_couplets.csv') %>%
                  filter(site_anon %in% site_list[7:12]))

couplets_ss_viz(process_output = read_csv(file = '../results/COMBINED_couplets.csv') %>%
                  filter(site_anon %in% site_list[13:18]))

couplets_ss_viz(process_output = read_csv(file = '../results/COMBINED_couplets.csv') %>%
                  filter(site_anon %in% site_list[19:23]))
```

# Multi Site Exploratory
```{r, fig.height=6}

couplets_ms_viz(read_csv(file = '../results/COMBINED_couplets.csv') %>%
                  filter(cohort=='cohort_1_denom_prop') %>% 
                  mutate(prop = round(prop, 2)) %>%
                  filter(! str_detect(site_anon,'all|ALL')), 'prop') +
  ggtitle('Proportion of Cohort 2 in Cohort 1')

```

# Anomaly Detection for Prop. Cohort 2 in Cohort 1

## Combined Networks
```{r}

cplt_anom <- trinetx_anom_detect(dat = read_csv(file = '../results/COMBINED_couplets.csv') %>%
                                   filter(cohort == 'cohort_1_denom_prop') %>% 
                                   filter(! str_detect(site_anon,'all|ALL')) %>% 
                                   mutate(prop = ifelse(is.na(prop), 0, prop),
                                          prop = prop * 100, 
                                          network = ifelse(grepl('HCO', site_anon), 
                                                           'trinetx', 'pedsnet')),
                                 var_col = 'prop',
                                 grp_vars = c('couplet_name'))

combo <- trinetx_anom_viz(dat = cplt_anom,
                 var_col = 'prop',
                 grp_col = 'couplet_name')

combo[[1]]
combo[[2]]


```

## Each Network Separately
```{r}

cplt_anom <- trinetx_anom_detect(dat = read_csv(file = '../results/COMBINED_couplets.csv') %>%
                                   filter(cohort == 'cohort_1_denom_prop') %>% 
                                   filter(! str_detect(site_anon,'all|ALL')) %>% 
                                   mutate(prop = ifelse(is.na(prop), 0, prop),
                                          prop = prop * 100, 
                                          network = ifelse(grepl('HCO', site_anon), 
                                                           'trinetx', 'pedsnet')),
                                 var_col = 'prop',
                                 grp_vars = c('couplet_name', 'network'))

combo <- trinetx_anom_viz(dat = cplt_anom,
                 var_col = 'prop',
                 grp_col = 'couplet_name')

combo[[1]]
combo[[2]]

```